name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: my-service-image:latest  # Replace with your service image
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl --fail http://localhost:5000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BE/requirements.txt
    - name: Wait for services to be ready
      run: sleep 30  # Adjust as necessary to ensure services are ready
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/devops-assignment-velklusia/devops-assignment-velklusia/tests" >> $GITHUB_ENV
    - name: Run tests
      run: pytest --junit-xml=report.xml
