name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create Docker network
      run: docker network create my-network

    - name: Start web service container
      run: docker run -d --network my-network --name web -p 5000:5000 my-service-image:latest

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BE/requirements.txt

    - name: Wait for services to be ready
      run: sleep 30  # Adjust as necessary to ensure services are ready

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/devops-assignment-velklusia/devops-assignment-velklusia/tests" >> $GITHUB_ENV

    - name: Run tests
      run: pytest --junit-xml=report.xml
