name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure Container Registry using environment variables directly
      - name: Login to Azure Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.ACR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login judevops.azurecr.io -u $DOCKER_USERNAME --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd BE
          docker build -t judevops.azurecr.io/klaudia_kluch-calculator:latest .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push judevops.azurecr.io/klaudia_kluch-calculator:latest
