name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login judevops.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t judevops.azurecr.io/klaudia_kluch-calculator:latest .
          docker push judevops.azurecr.io/klaudia_kluch-calculator:latest
