name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install what is needed for running the Back-end application in GitHub 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r BE/requirements.txt

      # Start the back end application...
      - name: Start Rest API
        run: python BE/calculator.py --rest &

      # Run the tests...
      - name: Run Unit Tests
        run: pytest tests/test_unit.py --junit-xml=unit_test_report.xml

      - name: Run API Tests
        run: pytest tests/test_api.py --junit-xml=api_test_report.xml

      # Publish the test results in GitHub...
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/*.xml'

      # Login to the Docker container registry
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and upload the docker image of the Back-end application...
      - name: Build and Push Calculator to Registry
        run: |
          docker build -t judevops.azurecr.io/klaudia-calculator ./BE
          docker push judevops.azurecr.io/klaudia-calculator
